### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /applications/haam-newsmagazine/

### ISSUE THREAD

**Issue by richardsun29** [daily-bruin/studentmedia-apply#5]
Traceback (most recent call last):

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)

 File "/home/django/django_project/apply/views.py", line 313, in publication
   return render(request,'publication.html',context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
   return HttpResponse(loader.render_to_string(*args, **kwargs),

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
   return t.render(context_instance)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
   return self._render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
   return self.nodelist.render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
   bit = self.render_node(node, context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
   return node.render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
   return compiled_parent._render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
   return self.nodelist.render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
   bit = self.render_node(node, context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
   return node.render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 389, in render
   return strip_spaces_between_tags(self.nodelist.render(context).strip())

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
   bit = self.render_node(node, context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
   return node.render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 203, in render
   nodelist.append(node.render(context))

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
   return nodelist.render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
   bit = self.render_node(node, context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
   return node.render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
   return nodelist.render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
   bit = self.render_node(node, context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
   return node.render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 203, in render
   nodelist.append(node.render(context))

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
   return nodelist.render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
   bit = self.render_node(node, context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/base.py", line 854, in render_node
   return node.render(context)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 447, in render
   six.reraise(*exc_info)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 433, in render
   url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 536, in reverse
   return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))

 File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 456, in _reverse_with_prefix
   (lookup_view_s, args, kwargs, len(patterns), patterns))

NoReverseMatch: Reverse for 'position' with arguments '()' and keyword arguments '{u'pos': u'', u'pub': u'haam-newsmagazine'}' not found. 1 pattern(s) tried: ['applications/(?P

**Comment by richardsun29** [comment]
#4 is the root cause of this
