### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error: /profile/

### ISSUE THREAD

**Issue by richardsun29** [daily-bruin/studentmedia-apply#7]
Traceback (most recent call last):

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/home/django/django_project/apply/views.py", line 228, in profile
    profile = form.save()

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/forms/models.py", line 446, in save
    construct=False)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/forms/models.py", line 99, in save_instance
    instance.save()

  File "/home/django/django_project/apply/models.py", line 146, in save
    super(Profile,self).save(*args,**kwargs)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 902, in execute_sql
    for sql, params in self.as_sql():

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 860, in as_sql
    for obj in self.query.objs

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 252, in pre_save
    file.save(file.name, file, save=False)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 86, in save
    self.name = self.storage.save(name, content)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/core/files/storage.py", line 48, in save
    name = self.get_available_name(name)

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/core/files/storage.py", line 73, in get_available_name
    while self.exists(name):

  File "/home/django/virtualenv_uclastudentmedia/local/lib/python2.7/site-packages/django/core/files/storage.py", line 244, in exists
    return os.path.exists(self.path(name))

  File "/home/django/virtualenv_uclastudentmedia/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 53-56: ordinal not in range(128)

**Comment by richardsun29** [comment]
It looks like this happens when someone creates/edits their profile. I left out the POST data for privacy, but it looks like its all valid ascii.
